import { Mail, MessageCircle } from 'lucide-react'
import { GlobeIcon } from '@/components/logo'

interface ReportFooterProps {
  publishedAt: string | null
  contactName: string | null
  contactEmail: string | null
}

export function ReportFooter({ publishedAt, contactName, contactEmail }: ReportFooterProps) {
  const dateStr = publishedAt
    ? new Date(publishedAt).toLocaleDateString('en-US', {
        month: 'long',
        day: 'numeric',
        year: 'numeric',
      })
    : null

  const hasContact = !!(contactName || contactEmail)

  return (
    <footer className="mt-16 pt-0 pb-12">
      {/* ── Contact card ── */}
      {hasContact && (
        <div className="border border-gray-100 rounded-2xl px-8 py-8 mb-12 bg-gray-50/50 print:bg-white print:border-gray-200">
          <div className="flex items-start gap-4">
            {/* Icon */}
            <div className="shrink-0 flex items-center justify-center w-10 h-10 rounded-full bg-[#C59C79]/10">
              <MessageCircle className="w-5 h-5 text-[#C59C79]" />
            </div>

            {/* Text block */}
            <div className="min-w-0">
              <p className="text-sm font-semibold text-gray-900">
                Questions about this report?
              </p>
              <p className="text-sm text-gray-500 mt-1 leading-relaxed">
                {contactName && contactEmail && (
                  <>
                    Reach out to{' '}
                    <span className="font-medium text-gray-700">{contactName}</span>
                    {' '}for any questions about deliverables, proof of performance,
                    or partnership details.
                  </>
                )}
                {contactName && !contactEmail && (
                  <>
                    Reach out to{' '}
                    <span className="font-medium text-gray-700">{contactName}</span>
                    {' '}for any questions about deliverables, proof of performance,
                    or partnership details.
                  </>
                )}
                {!contactName && contactEmail && (
                  <>
                    Get in touch if you have any questions about deliverables,
                    proof of performance, or partnership details.
                  </>
                )}
              </p>

              {/* Email link */}
              {contactEmail && (
                <a
                  href={`mailto:${contactEmail}`}
                  className="inline-flex items-center gap-2 mt-4 rounded-lg border border-[#C59C79]/20 bg-white px-4 py-2.5 text-sm font-medium text-[#C59C79] hover:bg-[#C59C79]/5 hover:border-[#C59C79]/40 transition-colors group print:border-gray-300 print:text-gray-700"
                >
                  <Mail className="w-4 h-4 text-[#C59C79]/60 group-hover:text-[#C59C79] transition-colors print:text-gray-500" />
                  {contactEmail}
                </a>
              )}
            </div>
          </div>
        </div>
      )}

      {/* ── Divider ── */}
      <div className="border-t border-gray-50 pt-10">
        {/* Attribution row */}
        <div className="flex items-center justify-between">
          <p className="text-sm text-gray-400">
            This report was generated by{' '}
            <a
              href="https://seira.global"
              target="_blank"
              rel="noopener noreferrer"
              className="inline-flex items-center gap-1 text-gray-500 hover:text-gray-700 transition-colors"
            >
              <GlobeIcon size={14} className="text-copper" />
              <span className="font-medium">seira</span>
            </a>
          </p>
          {dateStr && (
            <p className="text-sm text-gray-300">Generated on {dateStr}</p>
          )}
        </div>

        {/* Tagline */}
        <p className="text-xs text-gray-300 text-center mt-8">
          Powered by Seira — Sponsorship fulfillment, simplified.
        </p>
      </div>
    </footer>
  )
}
