import { GlobeIcon } from '@/components/logo'

interface ReportFooterProps {
  publishedAt: string | null
}

export function ReportFooter({ publishedAt }: ReportFooterProps) {
  const dateStr = publishedAt
    ? new Date(publishedAt).toLocaleDateString('en-US', {
        month: 'long',
        day: 'numeric',
        year: 'numeric',
      })
    : null

  return (
    <footer className="border-t border-gray-100 mt-16 pt-8 pb-12">
      <div className="flex items-center justify-between">
        <p className="text-sm text-gray-400">
          This report was generated by{' '}
          <a
            href="https://seira.global"
            target="_blank"
            rel="noopener noreferrer"
            className="inline-flex items-center gap-1 text-gray-500 hover:text-gray-700 transition-colors"
          >
            <GlobeIcon size={14} className="text-[#C59C79]" />
            <span className="font-medium">seira</span>
          </a>
        </p>
        {dateStr && (
          <p className="text-sm text-gray-300">Generated on {dateStr}</p>
        )}
      </div>
      <p className="text-xs text-gray-300 text-center mt-8">
        Powered by Seira — Sponsorship fulfillment, simplified.
      </p>
    </footer>
  )
}
