import type {
  Event,
  Plan,
  FlightOption,
  HotelOption,
  TransportSegment,
  ConstraintFlag,
} from "./types"

// ─── Full sample plan: Lakers vs Celtics ────────────────────────────

const lakersVsCelticsEvent: Event = {
  id: "evt-001",
  name: "Los Angeles Lakers vs Boston Celtics",
  date: "2026-02-14",
  startTime: "19:30",
  doorsTime: "18:00",
  endTimeEstimate: "22:00",
  timezone: "America/Los_Angeles",
  venue: {
    name: "Crypto.com Arena",
    address: "1111 S Figueroa St",
    city: "Los Angeles",
    state: "CA",
    country: "US",
    coordinates: { lat: 34.043, lng: -118.2673 },
  },
  category: "sports",
  imageUrl: undefined,
  sourceId: "tm-lakers-celtics-0214",
}

const outboundFlights: FlightOption[] = [
  {
    id: "fl-out-1",
    airline: "United",
    flightNumber: "UA 1422",
    departure: { airport: "ORD", time: "2026-02-14T08:15:00-06:00", city: "Chicago" },
    arrival: { airport: "LAX", time: "2026-02-14T10:45:00-08:00", city: "Los Angeles" },
    stops: 0,
    duration: "4h 30m",
    price: 289,
    timingTag: { label: "comfortable", severity: "comfortable", minutesBuffer: 432 },
  },
  {
    id: "fl-out-2",
    airline: "American",
    flightNumber: "AA 2187",
    departure: { airport: "ORD", time: "2026-02-14T07:00:00-06:00", city: "Chicago" },
    arrival: { airport: "LAX", time: "2026-02-14T11:30:00-08:00", city: "Los Angeles" },
    stops: 1,
    stopCities: ["Dallas"],
    duration: "6h 30m",
    price: 189,
    timingTag: { label: "comfortable", severity: "comfortable", minutesBuffer: 387 },
  },
  {
    id: "fl-out-3",
    airline: "Spirit",
    flightNumber: "NK 614",
    departure: { airport: "ORD", time: "2026-02-14T11:45:00-06:00", city: "Chicago" },
    arrival: { airport: "LAX", time: "2026-02-14T14:50:00-08:00", city: "Los Angeles" },
    stops: 0,
    duration: "5h 05m",
    price: 159,
    timingTag: { label: "tight arrival", severity: "tight", minutesBuffer: 190 },
  },
  {
    id: "fl-out-4",
    airline: "Frontier",
    flightNumber: "F9 328",
    departure: { airport: "ORD", time: "2026-02-14T13:20:00-06:00", city: "Chicago" },
    arrival: { airport: "LAX", time: "2026-02-14T16:15:00-08:00", city: "Los Angeles" },
    stops: 1,
    stopCities: ["Denver"],
    duration: "4h 55m",
    price: 139,
    timingTag: { label: "risky — 45 min buffer", severity: "risky", minutesBuffer: 45 },
  },
]

const returnFlights: FlightOption[] = [
  {
    id: "fl-ret-1",
    airline: "Delta",
    flightNumber: "DL 904",
    departure: { airport: "LAX", time: "2026-02-15T14:30:00-08:00", city: "Los Angeles" },
    arrival: { airport: "ORD", time: "2026-02-15T20:25:00-06:00", city: "Chicago" },
    stops: 0,
    duration: "3h 55m",
    price: 199,
    timingTag: { label: "comfortable", severity: "comfortable", minutesBuffer: 0 },
  },
  {
    id: "fl-ret-2",
    airline: "United",
    flightNumber: "UA 788",
    departure: { airport: "LAX", time: "2026-02-14T23:55:00-08:00", city: "Los Angeles" },
    arrival: { airport: "ORD", time: "2026-02-15T06:10:00-06:00", city: "Chicago" },
    stops: 0,
    duration: "4h 15m",
    price: 149,
    timingTag: { label: "feasible red-eye", severity: "tight", minutesBuffer: 115 },
  },
  {
    id: "fl-ret-3",
    airline: "Spirit",
    flightNumber: "NK 217",
    departure: { airport: "LAX", time: "2026-02-15T06:00:00-08:00", city: "Los Angeles" },
    arrival: { airport: "ORD", time: "2026-02-15T12:10:00-06:00", city: "Chicago" },
    stops: 0,
    duration: "4h 10m",
    price: 129,
    timingTag: { label: "too early after late game", severity: "risky", minutesBuffer: 0 },
  },
]

const hotels: HotelOption[] = [
  {
    id: "htl-1",
    name: "The Ritz-Carlton, Los Angeles",
    pricePerNight: 329,
    totalPrice: 329,
    nights: 1,
    rating: 4.7,
    distanceToVenue: { miles: 0.3, transitMinutes: 6, mode: "walk" },
    checkIn: "2026-02-14",
    checkOut: "2026-02-15",
    cluster: "near-venue",
  },
  {
    id: "htl-2",
    name: "Hotel Figueroa",
    pricePerNight: 219,
    totalPrice: 219,
    nights: 1,
    rating: 4.4,
    distanceToVenue: { miles: 0.8, transitMinutes: 5, mode: "drive" },
    checkIn: "2026-02-14",
    checkOut: "2026-02-15",
    cluster: "near-venue",
  },
  {
    id: "htl-3",
    name: "Courtyard by Marriott LA LIVE",
    pricePerNight: 179,
    totalPrice: 179,
    nights: 1,
    rating: 4.2,
    distanceToVenue: { miles: 1.5, transitMinutes: 8, mode: "drive" },
    checkIn: "2026-02-14",
    checkOut: "2026-02-15",
    cluster: "near-venue",
  },
  {
    id: "htl-4",
    name: "Holiday Inn Express DTLA",
    pricePerNight: 129,
    totalPrice: 129,
    nights: 1,
    rating: 3.9,
    distanceToVenue: { miles: 4.0, transitMinutes: 18, mode: "drive" },
    checkIn: "2026-02-14",
    checkOut: "2026-02-15",
    cluster: "value",
  },
  {
    id: "htl-5",
    name: "Motel 6 Los Angeles",
    pricePerNight: 79,
    totalPrice: 79,
    nights: 1,
    rating: 3.2,
    distanceToVenue: { miles: 7.0, transitMinutes: 32, mode: "drive" },
    checkIn: "2026-02-14",
    checkOut: "2026-02-15",
    cluster: "value",
  },
]

const groundTransport: TransportSegment[] = [
  {
    label: "LAX to hotel",
    distance: "18.2 mi",
    estimatedMinutes: 35,
    rideshareEstimate: "$28–$42",
    transitNote: "Metro C Line + E Line, ~55 min",
  },
  {
    label: "hotel to Crypto.com Arena",
    distance: "0.3 mi",
    estimatedMinutes: 6,
    rideshareEstimate: "$7–$12",
    transitNote: "walkable from most DTLA hotels",
  },
  {
    label: "Crypto.com Arena to hotel (post-game)",
    distance: "0.3 mi",
    estimatedMinutes: 12,
    rideshareEstimate: "$14–$28",
    lateNightNote: "expect 2-3x surge pricing after NBA games; allow 15-20 min for pickup",
  },
]

const constraintFlags: ConstraintFlag[] = [
  {
    id: "cf-1",
    type: "tight-arrival",
    severity: "danger",
    message: "Frontier F9 328 lands at 4:15 PM — only 45 min buffer before doors open at 6:00 PM, factoring LAX exit + transit",
    targetType: "flight",
    targetId: "fl-out-4",
  },
  {
    id: "cf-2",
    type: "hotel-far",
    severity: "warning",
    message: "Motel 6 is 7 mi from venue — 32 min drive, post-game transit will be longer with traffic",
    targetType: "hotel",
    targetId: "htl-5",
  },
  {
    id: "cf-3",
    type: "checkout-conflict",
    severity: "info",
    message: "Standard checkout is 11 AM — store luggage if taking an afternoon return flight",
  },
  {
    id: "cf-4",
    type: "late-egress",
    severity: "info",
    message: "Post-game rideshare surge expected; budget 2-3x normal pricing and 15-20 min wait",
    targetType: "transport",
  },
]

export const samplePlan: Plan = {
  id: "plan-001",
  event: lakersVsCelticsEvent,
  origin: { city: "Chicago", state: "IL", airportCode: "ORD" },
  travelDates: { arrive: "2026-02-14", depart: "2026-02-15" },
  flights: { outbound: outboundFlights, return: returnFlights },
  hotels,
  groundTransport,
  costEstimate: {
    min: 480,
    max: 720,
    breakdown: [
      { category: "flights (round-trip)", min: 268, max: 488 },
      { category: "hotel (1 night)", min: 79, max: 329 },
      { category: "ground transport", min: 49, max: 82 },
      { category: "food & misc", min: 40, max: 75 },
    ],
  },
  constraintFlags,
  selections: {},
  status: "ready",
  createdAt: "2026-02-10T09:00:00Z",
  updatedAt: "2026-02-10T09:00:00Z",
}

// ─── 12 Sample Events ──────────────────────────────────────────────

export const sampleEvents: Event[] = [
  lakersVsCelticsEvent,
  {
    id: "evt-002",
    name: "Inter Miami CF vs LAFC",
    date: "2026-03-07",
    startTime: "19:00",
    doorsTime: "17:30",
    endTimeEstimate: "21:00",
    timezone: "America/Los_Angeles",
    venue: {
      name: "BMO Stadium",
      address: "3939 S Figueroa St",
      city: "Los Angeles",
      state: "CA",
      country: "US",
      coordinates: { lat: 34.0128, lng: -118.2843 },
    },
    category: "sports",
  },
  {
    id: "evt-003",
    name: "Kansas City Chiefs vs Buffalo Bills",
    date: "2026-10-18",
    startTime: "13:00",
    doorsTime: "10:00",
    endTimeEstimate: "16:30",
    timezone: "America/Chicago",
    venue: {
      name: "GEHA Field at Arrowhead Stadium",
      address: "1 Arrowhead Dr",
      city: "Kansas City",
      state: "MO",
      country: "US",
      coordinates: { lat: 39.0489, lng: -94.4839 },
    },
    category: "sports",
  },
  {
    id: "evt-004",
    name: "New York Rangers vs Chicago Blackhawks",
    date: "2026-03-21",
    startTime: "19:00",
    doorsTime: "17:30",
    endTimeEstimate: "21:30",
    timezone: "America/New_York",
    venue: {
      name: "Madison Square Garden",
      address: "4 Pennsylvania Plaza",
      city: "New York",
      state: "NY",
      country: "US",
      coordinates: { lat: 40.7505, lng: -73.9934 },
    },
    category: "sports",
  },
  {
    id: "evt-005",
    name: "Beyonce — Renaissance World Tour",
    date: "2026-06-14",
    startTime: "20:00",
    doorsTime: "18:00",
    endTimeEstimate: "23:00",
    timezone: "America/Chicago",
    venue: {
      name: "Soldier Field",
      address: "1410 Special Olympics Dr",
      city: "Chicago",
      state: "IL",
      country: "US",
      coordinates: { lat: 41.8623, lng: -87.6167 },
    },
    category: "music",
  },
  {
    id: "evt-006",
    name: "Coachella Valley Music and Arts Festival",
    date: "2026-04-10",
    startTime: "12:00",
    doorsTime: "11:00",
    endTimeEstimate: "01:00",
    timezone: "America/Los_Angeles",
    venue: {
      name: "Empire Polo Club",
      address: "81800 Avenue 51",
      city: "Indio",
      state: "CA",
      country: "US",
      coordinates: { lat: 33.6803, lng: -116.2389 },
    },
    category: "festival",
  },
  {
    id: "evt-007",
    name: "Phoebe Bridgers — Punisher Tour",
    date: "2026-05-22",
    startTime: "20:30",
    doorsTime: "19:00",
    endTimeEstimate: "22:30",
    timezone: "America/Chicago",
    venue: {
      name: "The Riviera Theatre",
      address: "4746 N Racine Ave",
      city: "Chicago",
      state: "IL",
      country: "US",
      coordinates: { lat: 41.9681, lng: -87.6591 },
    },
    category: "music",
  },
  {
    id: "evt-008",
    name: "Billie Eilish — Hit Me Hard and Soft Tour",
    date: "2026-08-02",
    startTime: "20:00",
    doorsTime: "18:30",
    endTimeEstimate: "22:30",
    timezone: "America/New_York",
    venue: {
      name: "Madison Square Garden",
      address: "4 Pennsylvania Plaza",
      city: "New York",
      state: "NY",
      country: "US",
      coordinates: { lat: 40.7505, lng: -73.9934 },
    },
    category: "music",
  },
  {
    id: "evt-009",
    name: "Hamilton",
    date: "2026-04-18",
    startTime: "19:00",
    doorsTime: "18:00",
    endTimeEstimate: "22:00",
    timezone: "America/New_York",
    venue: {
      name: "Richard Rodgers Theatre",
      address: "226 W 46th St",
      city: "New York",
      state: "NY",
      country: "US",
      coordinates: { lat: 40.7590, lng: -73.9867 },
    },
    category: "theater",
  },
  {
    id: "evt-010",
    name: "Wicked — National Tour",
    date: "2026-05-10",
    startTime: "14:00",
    doorsTime: "13:00",
    endTimeEstimate: "17:00",
    timezone: "America/Chicago",
    venue: {
      name: "Cadillac Palace Theatre",
      address: "151 W Randolph St",
      city: "Chicago",
      state: "IL",
      country: "US",
      coordinates: { lat: 41.8845, lng: -87.6332 },
    },
    category: "theater",
  },
  {
    id: "evt-011",
    name: "Bonnaroo Music & Arts Festival",
    date: "2026-06-11",
    startTime: "11:00",
    doorsTime: "10:00",
    endTimeEstimate: "03:00",
    timezone: "America/Chicago",
    venue: {
      name: "Great Stage Park",
      address: "1560 New Bushy Branch Rd",
      city: "Manchester",
      state: "TN",
      country: "US",
      coordinates: { lat: 35.4754, lng: -86.0584 },
    },
    category: "festival",
  },
  {
    id: "evt-012",
    name: "Sundance Film Festival — Opening Night Premiere",
    date: "2026-01-22",
    startTime: "19:30",
    doorsTime: "18:30",
    endTimeEstimate: "22:00",
    timezone: "America/Denver",
    venue: {
      name: "Eccles Theatre",
      address: "1227 Center Dr",
      city: "Park City",
      state: "UT",
      country: "US",
      coordinates: { lat: 40.6461, lng: -111.4980 },
    },
    category: "film",
  },
]
